[project]
name = "tnt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astropy>=8.0.1",
    "equinox>=0.13.8",
    "galax",
    "jax>=0.4.30",
    "pyyaml>=6.0.3",
    "unxt>=1.11.4,<2",
]

[tool.uv.sources]
galax = { git = "https://github.com/GalacticDynamics/galax", branch = "main" }

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.20",
]
docs = [
    "myst-parser>=3.0.1",
    "pydata-sphinx-theme>=0.16.1",
    "sphinx>=7.4.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
extend-select = ["E501"]
