from hashlib import sha256
from pathlib import Path

import pytest
import yaml

from tnt.configuration import _semantic_configuration_sha256
from tnt.run_config_log import (
    RUN_CONFIG_LOG_FILENAME,
    ConfigurationSnapshotReference,
    RunConfigLog,
    RunManifestReference,
)


def _write_snapshot(
    tmp_path: Path,
    snapshot_id: int,
    config: dict[str, object],
) -> ConfigurationSnapshotReference:
    semantic_sha256 = _semantic_configuration_sha256(config)
    repository = tmp_path / "config_repository"
    path = (
        repository
        / "configurations"
        / f"{snapshot_id:04d}-{semantic_sha256[:8]}"
        / "resolved_config.yaml"
    )
    path.parent.mkdir(parents=True)
    path.write_text(
        f"# Generated by TNT: resolved configuration.\n"
        f"{yaml.safe_dump(config, sort_keys=False)}",
        encoding="utf-8",
    )
    return ConfigurationSnapshotReference.from_resolved_config(path)


def _write_run(
    tmp_path: Path,
    run_id: int,
    snapshot_id: int,
    config: dict[str, object],
) -> RunManifestReference:
    snapshot = _write_snapshot(tmp_path, snapshot_id, config)
    manifest_path = (
        snapshot.repository / "manifests" / f"{run_id:04d}-run_manifest.yaml"
    )
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest = {
        "manifest_version": 2,
        "run_id": run_id,
        "configuration": {
            "snapshot_id": snapshot.snapshot_id,
            "semantic_sha256": snapshot.semantic_sha256,
            "resolved": snapshot.resolved_config_path,
            "manifest": manifest_path.relative_to(snapshot.repository).as_posix(),
            "resolved_config_sha256": sha256(
                snapshot.absolute_resolved_config_path.read_bytes()
            ).hexdigest(),
        },
    }
    manifest_path.write_text(yaml.safe_dump(manifest), encoding="utf-8")
    return RunManifestReference.from_run_manifest(manifest_path)


def test_snapshot_reference_uses_portable_path_and_semantic_hash(
    tmp_path: Path,
) -> None:
    config = {"section": {"value": 1}, "items": ["first", "second"]}
    reference = _write_snapshot(tmp_path, 2, config)

    assert reference.repository == tmp_path / "config_repository"
    assert reference.snapshot_id == 2
    assert reference.semantic_sha256 == _semantic_configuration_sha256(config)
    assert (
        reference.resolved_config_path
        == f"configurations/0002-{reference.semantic_sha256[:8]}"
        "/resolved_config.yaml"
    )
    assert reference.absolute_resolved_config_path.is_file()


def test_run_manifest_reference_resolves_configuration_snapshot(
    tmp_path: Path,
) -> None:
    run = _write_run(tmp_path, 3, 1, {"value": 2})

    assert run.run_id == 3
    assert run.run_manifest_path == "manifests/0003-run_manifest.yaml"
    assert run.configuration_snapshot.snapshot_id == 1
    assert run.absolute_run_manifest_path.is_file()


def test_append_requires_cumulative_nonconflicting_iterations() -> None:
    log = RunConfigLog().append(0, 0)

    assert log.append(0, 0) is log
    with pytest.raises(ValueError, match="different TNT run"):
        log.append(0, 1)
    with pytest.raises(ValueError, match="Expected iteration 1"):
        log.append(2, 1)

    log = log.append(1, 1)
    assert list(log.table["iteration"]) == [0, 1]
    assert list(log.table["run_id"]) == [0, 1]


def test_write_and_read_round_trip_atomically(tmp_path: Path) -> None:
    first = _write_run(tmp_path, 0, 0, {"value": 1})
    second = _write_run(tmp_path, 1, 1, {"value": 2})
    path = first.repository / RUN_CONFIG_LOG_FILENAME

    RunConfigLog().append(0, first.run_id).write(path)
    log = RunConfigLog.read(path).append(1, second.run_id)
    log.write(path)
    restored = RunConfigLog.read(path)

    assert len(restored) == 2
    assert list(restored.table["run_id"]) == [0, 1]
    assert RunConfigLog.path_for(second.absolute_run_manifest_path) == path
    snapshots = restored.snapshot_references(
        first.repository,
        current_run_id=second.run_id,
        current_snapshot=second.configuration_snapshot,
    )
    assert [snapshot.semantic_sha256 for snapshot in snapshots] == [
        first.configuration_snapshot.semantic_sha256,
        second.configuration_snapshot.semantic_sha256,
    ]


def test_read_rejects_changed_resolved_snapshot(tmp_path: Path) -> None:
    run = _write_run(tmp_path, 0, 0, {"value": 1})
    path = run.repository / RUN_CONFIG_LOG_FILENAME
    RunConfigLog().append(0, run.run_id).write(path)
    run.configuration_snapshot.absolute_resolved_config_path.write_text(
        yaml.safe_dump({"value": 2}),
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="does not match its snapshot ID"):
        RunConfigLog.read(path)


def test_read_rejects_manifest_with_different_run_id(tmp_path: Path) -> None:
    run = _write_run(tmp_path, 0, 0, {"value": 1})
    path = run.repository / RUN_CONFIG_LOG_FILENAME
    RunConfigLog().append(0, run.run_id).write(path)
    manifest = yaml.safe_load(
        run.absolute_run_manifest_path.read_text(encoding="utf-8")
    )
    manifest["run_id"] = 1
    run.absolute_run_manifest_path.write_text(
        yaml.safe_dump(manifest), encoding="utf-8"
    )

    with pytest.raises(ValueError, match="records run_id 1, expected 0"):
        RunConfigLog.read(path)


def test_write_rejects_missing_run_manifest(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError, match="Run manifest does not exist"):
        RunConfigLog().append(0, 0).write(tmp_path / RUN_CONFIG_LOG_FILENAME)


def test_read_and_write_require_fixed_repository_filename(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match=RUN_CONFIG_LOG_FILENAME):
        RunConfigLog().write(tmp_path / "other.ecsv")
    with pytest.raises(ValueError, match=RUN_CONFIG_LOG_FILENAME):
        RunConfigLog.read(tmp_path / "other.ecsv")
