from pathlib import Path

import pytest
import yaml

from tnt.run_config_log import (
    RUN_CONFIG_LOG_FILENAME,
    RUN_IDS_WITHOUT_ITERATIONS_METADATA_KEY,
    TOTAL_RUNS_METADATA_KEY,
    RunConfigLog,
    RunManifestReference,
)


def _write_run(
    tmp_path: Path,
    run_id: int,
    config: dict[str, object],
) -> RunManifestReference:
    repository = tmp_path / "config_repository"
    run_directory = repository / "runs" / f"{run_id:04d}"
    run_directory.mkdir(parents=True)
    resolved_path = run_directory / "resolved_config.yaml"
    resolved_path.write_text(
        f"# Generated by TNT: resolved configuration.\n"
        f"{yaml.safe_dump(config, sort_keys=False)}",
        encoding="utf-8",
    )
    manifest_path = run_directory / "run_manifest.yaml"
    manifest = {
        "manifest_version": 3,
        "run_id": run_id,
        "configuration": {
            "resolved": resolved_path.relative_to(repository).as_posix(),
        },
    }
    manifest_path.write_text(yaml.safe_dump(manifest), encoding="utf-8")
    return RunManifestReference.from_run_manifest(manifest_path)


def test_run_manifest_reference_resolves_per_run_configuration(
    tmp_path: Path,
) -> None:
    run = _write_run(tmp_path, 3, {"value": 2})

    assert run.repository == tmp_path / "config_repository"
    assert run.run_id == 3
    assert run.run_manifest_path == "runs/0003/run_manifest.yaml"
    assert run.resolved_config_path == "runs/0003/resolved_config.yaml"
    assert run.absolute_run_manifest_path.is_file()
    assert run.absolute_resolved_config_path.is_file()


def test_append_requires_cumulative_nonconflicting_iterations() -> None:
    log = RunConfigLog().append(0, 0)

    assert log.append(0, 0) is log
    with pytest.raises(ValueError, match="different TNT run"):
        log.append(0, 1)
    with pytest.raises(ValueError, match="Expected iteration 1"):
        log.append(2, 1)

    log = log.append(1, 1)
    assert list(log.table["iteration"]) == [0, 1]
    assert list(log.table["run_id"]) == [0, 1]


def test_write_and_read_round_trip_atomically(tmp_path: Path) -> None:
    first = _write_run(tmp_path, 0, {"value": 1})
    second = _write_run(tmp_path, 1, {"value": 2})
    path = first.repository / RUN_CONFIG_LOG_FILENAME

    RunConfigLog().append(0, first.run_id).write(path)
    log = RunConfigLog.read(path).append(1, second.run_id)
    log.write(path)
    restored = RunConfigLog.read(path)

    assert len(restored) == 2
    assert list(restored.table["run_id"]) == [0, 1]
    assert restored.table.meta[TOTAL_RUNS_METADATA_KEY] == 2
    assert restored.table.meta[RUN_IDS_WITHOUT_ITERATIONS_METADATA_KEY] == []
    assert RunConfigLog.path_for(second.absolute_run_manifest_path) == path
    baseline = restored.baseline_run_reference(
        first.repository,
        current_run_id=second.run_id,
    )
    assert baseline == first


def test_metadata_records_runs_without_iterations(tmp_path: Path) -> None:
    first = _write_run(tmp_path, 0, {"value": 1})
    _write_run(tmp_path, 1, {"value": 2})
    third = _write_run(tmp_path, 2, {"value": 3})
    path = first.repository / RUN_CONFIG_LOG_FILENAME
    log = RunConfigLog().append(0, first.run_id).append(1, third.run_id)

    log.write(path)

    assert log.table.meta[TOTAL_RUNS_METADATA_KEY] == 3
    assert log.table.meta[RUN_IDS_WITHOUT_ITERATIONS_METADATA_KEY] == [1]


def test_read_refreshes_metadata_after_a_zero_iteration_run(tmp_path: Path) -> None:
    first = _write_run(tmp_path, 0, {"value": 1})
    path = first.repository / RUN_CONFIG_LOG_FILENAME
    RunConfigLog().append(0, first.run_id).write(path)
    _write_run(tmp_path, 1, {"value": 2})

    refreshed = RunConfigLog.read(path)

    assert refreshed.table.meta[TOTAL_RUNS_METADATA_KEY] == 2
    assert refreshed.table.meta[RUN_IDS_WITHOUT_ITERATIONS_METADATA_KEY] == [1]


def test_read_does_not_hash_archived_resolved_configuration(tmp_path: Path) -> None:
    run = _write_run(tmp_path, 0, {"value": 1})
    path = run.repository / RUN_CONFIG_LOG_FILENAME
    RunConfigLog().append(0, run.run_id).write(path)
    run.absolute_resolved_config_path.write_text(
        yaml.safe_dump({"value": 2}),
        encoding="utf-8",
    )

    restored = RunConfigLog.read(path)

    assert len(restored) == 1


def test_read_rejects_manifest_with_different_run_id(tmp_path: Path) -> None:
    run = _write_run(tmp_path, 0, {"value": 1})
    path = run.repository / RUN_CONFIG_LOG_FILENAME
    RunConfigLog().append(0, run.run_id).write(path)
    manifest = yaml.safe_load(
        run.absolute_run_manifest_path.read_text(encoding="utf-8")
    )
    manifest["run_id"] = 1
    run.absolute_run_manifest_path.write_text(
        yaml.safe_dump(manifest), encoding="utf-8"
    )

    with pytest.raises(ValueError, match="records run_id 1, expected 0"):
        RunConfigLog.read(path)


def test_write_rejects_missing_run_manifest(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError, match="Run manifest does not exist"):
        RunConfigLog().append(0, 0).write(tmp_path / RUN_CONFIG_LOG_FILENAME)


def test_read_and_write_require_fixed_repository_filename(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match=RUN_CONFIG_LOG_FILENAME):
        RunConfigLog().write(tmp_path / "other.ecsv")
    with pytest.raises(ValueError, match=RUN_CONFIG_LOG_FILENAME):
        RunConfigLog.read(tmp_path / "other.ecsv")
