from pathlib import Path

import pytest
import yaml

from tnt.configuration import _semantic_configuration_sha256
from tnt.iteration_config_log import (
    ITERATION_CONFIG_LOG_FILENAME,
    ConfigurationSnapshotReference,
    IterationConfigLog,
)


def _write_snapshot(
    tmp_path: Path,
    snapshot_id: int,
    config: dict[str, object],
) -> ConfigurationSnapshotReference:
    semantic_sha256 = _semantic_configuration_sha256(config)
    repository = tmp_path / "config_repository"
    path = (
        repository
        / "configurations"
        / f"{snapshot_id:04d}-{semantic_sha256[:8]}"
        / "resolved_config.yaml"
    )
    path.parent.mkdir(parents=True)
    path.write_text(
        f"# Generated by TNT: resolved configuration.\n"
        f"{yaml.safe_dump(config, sort_keys=False)}",
        encoding="utf-8",
    )
    return ConfigurationSnapshotReference.from_resolved_config(path)


def test_snapshot_reference_uses_portable_path_and_semantic_hash(
    tmp_path: Path,
) -> None:
    config = {"section": {"value": 1}, "items": ["first", "second"]}
    reference = _write_snapshot(tmp_path, 2, config)

    assert reference.repository == tmp_path / "config_repository"
    assert reference.snapshot_id == 2
    assert reference.semantic_sha256 == _semantic_configuration_sha256(config)
    assert (
        reference.resolved_config_path
        == f"configurations/0002-{reference.semantic_sha256[:8]}"
        "/resolved_config.yaml"
    )
    assert reference.absolute_resolved_config_path.is_file()


def test_append_requires_cumulative_nonconflicting_iterations(tmp_path: Path) -> None:
    first = _write_snapshot(tmp_path, 0, {"value": 1})
    second = _write_snapshot(tmp_path, 1, {"value": 2})

    log = IterationConfigLog().append(0, first)
    assert log.append(0, first) is log
    with pytest.raises(ValueError, match="different configuration snapshot"):
        log.append(0, second)
    with pytest.raises(ValueError, match="Expected iteration 1"):
        log.append(2, second)

    log = log.append(1, second)
    assert list(log.table["iteration"]) == [0, 1]
    assert list(log.table["configuration_snapshot_id"]) == [0, 1]


def test_write_and_read_round_trip_atomically(tmp_path: Path) -> None:
    first = _write_snapshot(tmp_path, 0, {"value": 1})
    second = _write_snapshot(tmp_path, 1, {"value": 2})
    path = first.repository / ITERATION_CONFIG_LOG_FILENAME

    IterationConfigLog().append(0, first).write(path)
    log = IterationConfigLog.read(path).append(1, second)
    log.write(path)
    restored = IterationConfigLog.read(path)

    assert len(restored) == 2
    assert list(restored.table["semantic_sha256"]) == [
        first.semantic_sha256,
        second.semantic_sha256,
    ]
    assert IterationConfigLog.path_for(second.absolute_resolved_config_path) == path


def test_read_rejects_changed_resolved_snapshot(tmp_path: Path) -> None:
    reference = _write_snapshot(tmp_path, 0, {"value": 1})
    path = reference.repository / ITERATION_CONFIG_LOG_FILENAME
    IterationConfigLog().append(0, reference).write(path)
    reference.absolute_resolved_config_path.write_text(
        yaml.safe_dump({"value": 2}),
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="does not match its snapshot ID"):
        IterationConfigLog.read(path)


def test_write_requires_fixed_repository_filename(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match=ITERATION_CONFIG_LOG_FILENAME):
        IterationConfigLog().write(tmp_path / "other.ecsv")
